defaults: &defaults
  docker:
  - image: circleci/golang:1.12

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Build Docker container
          command: docker build -t navikt/naiserator:latest .
      - run:
          name: Save Docker container
          command: docker save navikt/naiserator:latest -o /tmp/workspace/docker-image.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image.tar
  release:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "23:30:b7:2a:e9:44:5f:d9:d0:fd:e9:ce:7b:1d:0a:96"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker container
          command: docker load -i /tmp/workspace/docker-image.tar
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Docker container
          command: |
            version=$(./version.sh)
            docker tag navikt/naiserator:latest navikt/naiserator:${version}
            docker push navikt/naiserator:latest
            docker push navikt/naiserator:${version}
      - run:
          name: Deploy new version to Kubernetes
          command: |
            version=$(./version.sh)
            naisyaml=$(mktemp -d)
            res="hack/resources"
            static_file="${naisyaml}/templates/zz-generated-naiserator.yaml"
            git clone git@github.com:navikt/nais-yaml $naisyaml
            cat $res/00-namespace.yaml $res/01-serviceaccount.yaml $res/02-clusterrole.yaml $res/03-clusterrolebinding.yaml config/*.yaml > $static_file
            cd $naisyaml
            sed -E -i "s#image: navikt/naiserator:.+#image: navikt/naiserator:${version}#" vars/naiserator.yaml
            git add .
            git --no-pager diff --cached
            git commit -a -m "Bump Naiserator to version ${version}"
            git push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
