
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: applications.nais.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .metadata.labels.team
    name: Team
    type: string
  - JSONPath: .status.synchronizationState
    name: State
    type: string
  group: nais.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    singular: application
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: Application defines a NAIS application.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationSpec contains the NAIS manifest.
          properties:
            accessPolicy:
              properties:
                inbound:
                  properties:
                    rules:
                      items:
                        properties:
                          application:
                            type: string
                          cluster:
                            type: string
                          namespace:
                            type: string
                        required:
                        - application
                        type: object
                      type: array
                  required:
                  - rules
                  type: object
                outbound:
                  properties:
                    external:
                      items:
                        properties:
                          host:
                            type: string
                          ports:
                            items:
                              properties:
                                name:
                                  type: string
                                port:
                                  format: int32
                                  type: integer
                                protocol:
                                  enum:
                                  - HTTP
                                  - HTTPS
                                  - GRPC
                                  - HTTP2
                                  - MONGO
                                  - TCP
                                  - TLS
                                  type: string
                              required:
                              - name
                              - port
                              - protocol
                              type: object
                            type: array
                        required:
                        - host
                        type: object
                      type: array
                    rules:
                      items:
                        properties:
                          application:
                            type: string
                          cluster:
                            type: string
                          namespace:
                            type: string
                        required:
                        - application
                        type: object
                      type: array
                  type: object
              type: object
            azure:
              properties:
                application:
                  properties:
                    enabled:
                      type: boolean
                    replyURLs:
                      items:
                        type: string
                      type: array
                    tenant:
                      enum:
                      - nav.no
                      - trygdeetaten.no
                      type: string
                  required:
                  - enabled
                  type: object
              required:
              - application
              type: object
            env:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                  valueFrom:
                    properties:
                      fieldRef:
                        properties:
                          fieldPath:
                            enum:
                            - ""
                            - metadata.name
                            - metadata.namespace
                            - metadata.labels
                            - metadata.annotations
                            - spec.nodeName
                            - spec.serviceAccountName
                            - status.hostIP
                            - status.podIP
                            type: string
                        required:
                        - fieldPath
                        type: object
                    required:
                    - fieldRef
                    type: object
                required:
                - name
                type: object
              type: array
            envFrom:
              items:
                properties:
                  configmap:
                    type: string
                  secret:
                    type: string
                type: object
              type: array
            filesFrom:
              items:
                properties:
                  configmap:
                    type: string
                  mountPath:
                    type: string
                  secret:
                    type: string
                type: object
              type: array
            gcp:
              properties:
                buckets:
                  items:
                    properties:
                      cascadingDelete:
                        type: boolean
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
                sqlInstances:
                  items:
                    properties:
                      autoBackupHour:
                        maximum: 23
                        minimum: 0
                        type: integer
                      cascadingDelete:
                        type: boolean
                      databases:
                        items:
                          properties:
                            envVarPrefix:
                              type: string
                            name:
                              type: string
                          required:
                          - name
                          type: object
                        type: array
                      diskAutoresize:
                        type: boolean
                      diskSize:
                        minimum: 10
                        type: integer
                      diskType:
                        enum:
                        - SSD
                        - HDD
                        type: string
                      highAvailability:
                        type: boolean
                      maintenance:
                        properties:
                          day:
                            maximum: 7
                            minimum: 1
                            type: integer
                          hour:
                            maximum: 23
                            minimum: 0
                            type: integer
                        type: object
                      name:
                        type: string
                      tier:
                        pattern: db-.+
                        type: string
                      type:
                        enum:
                        - POSTGRES_11
                        - POSTGRES_12
                        type: string
                    required:
                    - type
                    type: object
                  type: array
              type: object
            idporten:
              properties:
                clientURI:
                  type: string
                enabled:
                  type: boolean
                frontchannelLogoutURI:
                  type: string
                postLogoutRedirectURIs:
                  items:
                    type: string
                  type: array
                redirectURI:
                  type: string
                refreshTokenLifetime:
                  type: integer
              required:
              - enabled
              type: object
            image:
              type: string
            ingresses:
              items:
                type: string
              type: array
            kafka:
              properties:
                pool:
                  type: string
              required:
              - pool
              type: object
            leaderElection:
              type: boolean
            liveness:
              description: Liveness probe and readiness probe definitions.
              properties:
                failureThreshold:
                  type: integer
                initialDelay:
                  type: integer
                path:
                  type: string
                periodSeconds:
                  type: integer
                port:
                  type: integer
                timeout:
                  type: integer
              required:
              - path
              type: object
            logformat:
              enum:
              - ""
              - accesslog
              - accesslog_with_processing_time
              - accesslog_with_referer_useragent
              - capnslog
              - logrus
              - gokit
              - redis
              - glog
              - simple
              - influxdb
              - log15
              type: string
            logtransform:
              type: string
            port:
              type: integer
            preStopHookPath:
              type: string
            prometheus:
              properties:
                enabled:
                  type: boolean
                path:
                  type: string
                port:
                  type: string
              type: object
            readiness:
              description: Liveness probe and readiness probe definitions.
              properties:
                failureThreshold:
                  type: integer
                initialDelay:
                  type: integer
                path:
                  type: string
                periodSeconds:
                  type: integer
                port:
                  type: integer
                timeout:
                  type: integer
              required:
              - path
              type: object
            replicas:
              properties:
                cpuThresholdPercentage:
                  description: Amount of CPU usage before the autoscaler kicks in.
                  type: integer
                max:
                  description: The pod autoscaler will scale deployments on demand
                    until this maximum has been reached.
                  type: integer
                min:
                  description: The minimum amount of replicas acceptable for a successful
                    deployment.
                  type: integer
              type: object
            resources:
              properties:
                limits:
                  properties:
                    cpu:
                      pattern: ^\d+m?$
                      type: string
                    memory:
                      pattern: ^\d+[KMG]i$
                      type: string
                  type: object
                requests:
                  properties:
                    cpu:
                      pattern: ^\d+m?$
                      type: string
                    memory:
                      pattern: ^\d+[KMG]i$
                      type: string
                  type: object
              type: object
            secureLogs:
              properties:
                enabled:
                  description: Whether or not to enable a sidecar container for secure
                    logging.
                  type: boolean
              required:
              - enabled
              type: object
            service:
              properties:
                name:
                  enum:
                  - grpc
                  - grpc-web
                  - http
                  - http2
                  - https
                  - mongo
                  - mysql
                  - redis
                  - tcp
                  - tls
                  - udp
                  type: string
                port:
                  format: int32
                  type: integer
              required:
              - port
              type: object
            skipCaBundle:
              type: boolean
            startup:
              description: Liveness probe and readiness probe definitions.
              properties:
                failureThreshold:
                  type: integer
                initialDelay:
                  type: integer
                path:
                  type: string
                periodSeconds:
                  type: integer
                port:
                  type: integer
                timeout:
                  type: integer
              required:
              - path
              type: object
            strategy:
              properties:
                type:
                  enum:
                  - Recreate
                  - RollingUpdate
                  type: string
              required:
              - type
              type: object
            tokenx:
              properties:
                enabled:
                  description: if enabled, the application will have a jwker secret
                    injected
                  type: boolean
                mountSecretsAsFilesOnly:
                  description: if enabled, secrets for TokenX will be mounted as files
                    only, i.e. not as env.
                  type: boolean
              required:
              - enabled
              type: object
            vault:
              properties:
                enabled:
                  type: boolean
                paths:
                  items:
                    properties:
                      format:
                        enum:
                        - flatten
                        - json
                        - yaml
                        - env
                        - properties
                        - ""
                        type: string
                      kvPath:
                        type: string
                      mountPath:
                        type: string
                    required:
                    - kvPath
                    - mountPath
                    type: object
                  type: array
                sidecar:
                  type: boolean
              type: object
            webproxy:
              type: boolean
          required:
          - image
          type: object
        status:
          description: ApplicationStatus contains different NAIS status properties
          properties:
            correlationID:
              type: string
            deploymentRolloutStatus:
              type: string
            rolloutCompleteTime:
              format: int64
              type: integer
            synchronizationHash:
              type: string
            synchronizationState:
              type: string
            synchronizationTime:
              format: int64
              type: integer
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
